[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["idlewith <newellzhou@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
